adobecom/nala

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Added markdown files needed for base setup.
> Added Markdown files

- CONTRIBUTING.md
added release management section
> updated contributing markdown file

- .vscode/extensions.json
- .vscode/settings.json
VSCode extensions recommendations file added.
Settings set to enforce tabSize to 2.
> VSCode Ext. Recommendations

- tests/columns.test.js
removed hook for closing page, found issues across github for playwright with hooks causing premature closures.
> removed hook for closing page

- features/columns.spec.js
- tests/columns.test.js
Adjusted the columns test so there are fewer test executions and only a quick validation of visibility and expected amounts of columns.
> updated Columns Test

- .eslintrc.js
- envs/envs.js
- features/columns.spec.js
- features/howto.spec.js
- features/marquee.spec.js
- features/parse.js
- package-lock.json
- package.json
- playwright.config.js
- selectors/columns.selectors.js
- selectors/marquee.selectors.js
- tests/columns.test.js
- tests/marquee.test.js
- Added ESLint and configuration
- Updated files to comply with ESLint findings.
> ESLint Added

- .github/workflows/self.yml
- action.yml
- features/parse.js
- package-lock.json
- run.sh
- tests/marquee.test.js
* Add action to be run by other projects
> MWPW-109693 - Support Projects

- .github/workflows/daily.yml
- CONTRIBUTING.md
- action.yml
- features/failedblock.spec.js
- package-lock.json
- package.json
- playwright.config.js
- run.sh
- selectors/failedblock.selectors.js
- tests/failedblock.test.js
* Changed branding
* Added daily test run
* Modified failed block slightly
> Nala Rebrand

- features/failedblock.spec.js
removed duplicate block pages so testing has more value
> removed duplicate block pages

- features/failedblock.spec.js
> fixed small typo

- package-lock.json
- package.json
- tests/imslogin.test.js
Fixes ticket: [MWPW-123295](https://jira.corp.adobe.com/browse/MWPW-123295)
- Addresses timeout failures in IMSLogin Test for two test cases against WebKit browsers, see ticket for more details.
- Updates Playwright version and Dev dependencies to most recent releases.
> Daily runs fix

- tests/modal.test.js
updated modal test for workaround of ticket MWPW-123567.
> modal test workaround for MWPW-123567

- features/parse.js
Fixes ticket [MWPW-123294](https://jira.corp.adobe.com/browse/MWPW-123294)
- Added condition check for branch directory '/' in sent-in branch from the environment
- Split branch value upon finding the '/' directory
- Create branch variable based on two substrings
> Feature branch directory parsing update

- features/faas.spec.js
- selectors/faas.selectors.js
- tests/faas.test.js
Fix for modal not showing up when directly navigating to the #url when using milolibs url parameter.
> Fix for modal not showing up

- .github/workflows/daily.yml
- .github/workflows/debug.yml
- .github/workflows/manual.yml
- .github/workflows/self.yml
Updated github actions for upload-artifact to latest version v3.
> Updated github actions for upload-artifact

- features/carousel.spec.js
- selectors/carousel.selectors.js
- tests/carousel.test.js
Ticket:[MWPW-122174]( https://jira.corp.adobe.com/browse/MWPW-122174 )
Added Carousel tests that verifies the following:
- Verify a Carousel with buttons/links inside is clickable and functions correctly.
- Verify Carousel slider controls forward and backward, test content has changed.
- Verify Carousel dot controls by clicking forward and backward, test content has changed. 
There's a tabbing issue so I'll break the accessibility portion out into another ticket to do after the issue is resolved.
> Added carousel tests

- features/imslogin.spec.js
- tests/carousel.test.js
fixed IMS login test bacom prod url, removed unnecessary awaits.
> fixed IMS login test bacom prod url

- utils/extract-test-title.js
> Added stage url check

- envs/envs.js
added staging environment for BACOM
> added staging environment for BACOM

- features/failedblock.spec.js
- features/imslogin.spec.js
- tests/carousel.test.js
- tests/faas.test.js
- tests/imslogin.test.js
This PR addresses failures in the daily runs as well as adds missing failed block tests for DC.
Most of the tests in the daily runs were failing due to internal network access denied issues and browser bot issues.  These tests are being skipped temporarily until a solution is in place that will work.
> Addressing failures in Daily Runs

- tests/dc/converter_L1.test.js
- tests/dc/converter_L2.test.js
- tests/imslogin.test.js
- utils/imslogin.js
Jira ticket: [MWPW-123530](https://jira.corp.adobe.com/browse/MWPW-123530)
Validates the redirect URLs of Frictionless pages if the visitor is already signed-in.
Test URLs:
https://www.adobe.com/acrobat/online/sign-pdf.html
https://www.adobe.com/acrobat/online/request-signature.html
https://www.adobe.com/acrobat/online/crop-pdf.html
https://www.adobe.com/acrobat/online/delete-pdf-pages.html
https://www.adobe.com/acrobat/online/rotate-pdf.html
https://www.adobe.com/acrobat/online/rearrange-pdf.html
https://www.adobe.com/acrobat/online/split-pdf.html
https://www.adobe.com/acrobat/online/add-pages-to-pdf.html
https://www.adobe.com/acrobat/online/extract-pdf-pages.html
https://www.adobe.com/acrobat/online/pdf-editor.html
https://www.adobe.com/acrobat/online/merge-pdf.html …
> DC sign in tests

- package-lock.json
- package.json
Updated playwright to v1.32.1 and dev dependencies to latest versions.
> Updated playwright and dev dependencies

- selectors/milo/georouting.selectors.js
Fixed text check for Georouting
> Fixed text check for Georouting

- package-lock.json
- package.json
updated playwright to latest patch
> updated playwright to latest patch

- features/milo/failedblock.spec.js
- tests/milo/failedblock.test.js
-  Updated test urls for BACOM with the current high value pages. 
- Added a 200 check since the tests were passing on 404 pages before.
> Updated bacom urls for failedBlocks test.

- features/bacom/stats.spec.js
- selectors/bacom/stats.page.js
- tests/bacom/stat.test.js
Adding tests for the stats block on bacom.
Ticket: https://jira.corp.adobe.com/browse/MWPW-126249
> Adding stats block test.

- features/bacom/tree-view.spec.js
- selectors/bacom/tree-view.page.js
- tests/bacom/tree-view.test.js
Adding tests for the tree-view block.
Ticket:
https://jira.corp.adobe.com/browse/MWPW-126246
> Adding treeview tests

- features/milo/media.block.spec.js
- libs/webutil.js
- selectors/milo/media.block.page.js
- tests/milo/media.block.test.js
[MWPW-130435](https://jira.corp.adobe.com/browse/MWPW-130435): Media block automation test scripts
PR includes:
- Automation test scripts for the following features of Media block
- Media (small)
- Media
- Media (large, dark)
- Enhanced `verifyAttributes()` method of `WebUtil` for accommodating `classes`
> MWPW-130435 : Media block block automation test scripts

- configs/acom.config.js
- configs/bacom.config.js
- configs/blog.config.js
- configs/dc.config.js
- configs/feds.config.js
- configs/milo.config.js
- playwright.config.js
[MWPW-130636](https://jira.corp.adobe.com/browse/MWPW-130636) Update the test folder path in the `config.js` files for all consumer projects
PR fixes the below issue: 
- **Issue**:  If the PR Label has a project i.e. `run-milo-live` and does not have any `tags i.e. @marquee or @howto`, then all nala tests are running.
- **Expected**: If the PR Label has a project and no tags, then it should execute the test corresponding to the project.
> MWPW-130636 : Update test folder path in configs

- envs/envs.js
- features/milo/failedblock.spec.js
Added two urls to failed block test for adobe stock.
> Added two urls to failed block test

- configs/feds.config.js
- features/feds/consent.spec.js
- features/feds/footer.spec.js
- features/feds/header.spec.js
- features/feds/search.spec.js
- features/feds/userprofile.spec.js
[MWPW-132464](https://jira.corp.adobe.com/browse/MWPW-132464): Move FEDS Nala checks to @milo_live
> [MWPW-132464] Move FEDS checks to @milo_live env

- configs/cc.config.js
- configs/dc.config.js
- configs/milo.config.js
- playwright.config.js
PR includes
- Remove urls that are using `hlx.page` from `env.js` and `.config.js`
> Update the urls

- features/milo/icon.block.spec.js
- selectors/milo/icon.block.page.js
- tests/milo/icon.block.test.js
[MWPW-133863 ](https://jira.corp.adobe.com/browse/MWPW-133863 ): Icon block tests scripts
PR includes 
- Automation test scripts for the following features of the Icon block
- Icon block (fullwidth, medium) 
- Icon block (fullwidth, medium, intro)
- Icon block (fullwidth,large)
> MWPW-133863 : Icon block tests scripts

- configs/bacom.config.js
- features/bacom/event-speakers.spec.js
- selectors/bacom/event-speakers.page.js
- tests/bacom/event-speakers.test.js
Adding tests for event-speakers block.
Ticket: https://jira.corp.adobe.com/browse/MWPW-126250
> Adding event speakers tests

- selectors/milo/howto.block.page.js
- tests/milo/faas.block.test.js
- tests/milo/georouting.feature.test.js
- tests/milo/htmlextn.feature.test.js
PR includes
Fix for following failures.
- HowTo Block test scripts fixes as per [Milo PR - 879](https://github.com/adobecom/milo/pull/879)
- Georouting Feature 
- for the WebKit browser, test case # 5 is skipped
- HtmlExtn Features
- scripts require an update as per the updated template, so skipping existing scripts run
> MWPW-134592 : Fixing daily run failures

- .github/workflows/manual.yml
- features/milo/carousel.block.spec.js
- selectors/milo/carousel.block.page.js
- tests/milo/carousel.block.test.js
This PR fixes the following.
- Carouse block script fix for GitHub latest Windows (Windows - 2022 server)  platform
Note: This is a bit high priority, as it is part of daily run scripts
> [ Daily Run] Carouse block script fix for Windows platform

- selectors/milo/columns.block.page.js
- selectors/milo/zpattern.block.page.js
PR includes
Fix for following failures.
- Columns Block test scripts fixes as per [Milo PR - 1070](https://github.com/adobecom/milo/pull/1070)
> MWPW-134592 : Fixing daily run failures ( Columns-block )

- .github/workflows/manual.yml
- selectors/milo/accordion.block.page.js
- selectors/milo/carousel.block.page.js
- selectors/milo/columns.block.page.js
- selectors/milo/georouting.feature.page.js
- selectors/milo/howto.block.page.js
- selectors/milo/icon.block.page.js
- selectors/milo/marquee.block.page.js
- selectors/milo/media.block.page.js
- selectors/milo/modal.block.page.js
- selectors/milo/quote.block.page.js
- selectors/milo/review.block.page.js
- selectors/milo/text.block.page.js
- selectors/milo/zpattern.block.page.js
- tests/milo/accordion.block.test.js
- tests/milo/carousel.block.test.js
- tests/milo/columns.block.test.js
- tests/milo/georouting.feature.test.js
- tests/milo/howto.block.test.js
- tests/milo/icon.block.test.js
- tests/milo/marquee.block.test.js
- tests/milo/media.block.test.js
- tests/milo/modal.block.test.js
- tests/milo/quote.block.test.js
- tests/milo/review.block.test.js
- tests/milo/text.block.test.js
- tests/milo/zpattern.block.test.js
[MWPW-135502](https://jira.corp.adobe.com/browse/MWPW-135502): 
PR Includes
- All blocks page object classes are updated to default from named entity classes.
- Skipping Georouting test cases execution for latest-windows & webkit configuration as they are failing
> MWPW-135502: Update page object class from named entity class to default class 

- run.sh
PR Includes:
- Reverting `run.sh` to the earlier version
cc : @amauch-adobe
> Reverting run.sh to earlier version

- envs/envs.js
- features/blog/sitemap.spec.js
- tests/blog/sitemap.test.js
[MWPW-136173 ](https://jira.corp.adobe.com/browse/MWPW-136173 ): Blog Sitemaps automation test script
PR includes 
- Automation test scripts for the following sitemap.xmls
-   '/en/sitemap.xml',
-  '/de/sitemap.xml',
-  '/ko/sitemap.xml',
-  '/es/sitemap.xml',
-  '/fr/sitemap.xml',
- '/it/sitemap.xml',
- '/jp/sitemap.xml',
- '/br/sitemap.xml',
> MWPW-136173 : Blog Sitemaps automation test script

- playwright.config.js
- utils/reporters/base-reporter.js
PR Includes
- Update to `base reporter` class.
- removed the need to extra file/method ( i.e. `extract-test-title.js`)
Note: This is a work in progress for other enhancements, and this change does not impact any functionality.
> Update base reporter class

- .github/workflows/self.yml
- global.setup.js
- playwright.config.js
- run.sh
- tests/milo/accordion.block.test.js
PR Includes
- This is work in progress test PR, it does not impact any of the existing test/code.
-
Please need aproval
> PR branch test 

- playwright.config.js
- run.sh
This is a continuation of [PR-170](https://github.com/adobecom/nala/pull/170), for executing tests on pr branch
> PR Branch Run 

- run.sh
- selectors/milo/modal.block.page.js
PR includes a fix for the following 
- Modal class attribute update  from: ` class: 'modal link-block'` To ` class: 'modal link-block '`
> [Modal ] Modal class attribute fix

- global.setup.js
- libs/baseurl.js
- playwright.config.js
- run.sh
PR includes
- Update local test execution url
- Clean up of print statements
- Update to playwright.config.js. for baseURL and workers count
> PR branch test execution

- features/milo/figure.block.spec.js
- run.sh
- selectors/milo/figure.block.page.js
- tests/milo/figure.block.test.js
PR includes 
- [MWPW-136931](https://jira.corp.adobe.com/browse/MWPW-136931 ): Automation test scripts for the following features of the Figure block
- Figure block (Image with caption)
- Figure block (Multiple images with caption)
>  [MWPW-136931] : Figure block tests scripts

- features/milo/video.block.spec.js
- selectors/milo/accordion.block.page.js
- selectors/milo/video.block.page.js
- tests/milo/accordion.block.test.js
- tests/milo/video.block.test.js
[MWPW-138097](https://jira.corp.adobe.com/browse/MWPW-138097 ): Video block tests scripts
PR includes 
- Automation test scripts for the following features of the Video block
- Video Default 
- Video autoplay loop
- Video autoplay loop once
- Video hover play
- Refactoring of Accordion scripts
- Accordion
- Accordion (seo)
- Accordion (quiet, max-width-12-desktop-large)
> MWPW-138097 : Video block automation test scripts

- playwright.config.js
- run.sh
PR Includes:
- Temporarily commenting Github Ubuntu - WebKit run,
> commenting linux-webkit project

- features/milo/card.block.spec.js
- selectors/milo/card.block.page.js
- tests/milo/card.block.test.js
[MWPW-139022](https://jira.corp.adobe.com/browse/MWPW-139022 ): Card Block tests scripts
PR includes 
- Automation test scripts for the following features of the Card block
- Card
- Card (half-card, border)
- Card (double-width-card, border)
- Card (product-card, border)
- Card (half-height-card, border)
- Card-horizontal
- Card-horizontal (tile)
> [MWPW-139022] : Card block tests scripts

- features/milo/chart.block.spec.js
- selectors/milo/chart.block.page.js
- tests/milo/chart.block.test.js
[MWPW-139085](https://jira.corp.adobe.com/browse/MWPW-139085 ): Chart Block tests scripts
PR includes 
- Automation test scripts for the following features of the Chart block
- Chart (area, green, border)
- Chart (bar, border)
- Chart (column, border)
- Chart (donut, border)
- Chart (line, border)
- Chart (oversized-number, border)
- Chart (pie, border)
> [MWPW-139085] : Chart block tests scripts

- features/milo/table.block.spec.js
- selectors/milo/table.block.page.js
- tests/milo/table.block.test.js
- utils/reporters/base-reporter.js
[MWPW-139138](https://jira.corp.adobe.com/browse/MWPW-139138 ): Table Block tests scripts
PR includes 
- Automation test scripts for the following features of the Table block
- Table (default)
- Table (highlight)
- Table (sticky)
- Table (highlight, collapse, sticky)
- Table (merch)
> [MWPW-139138] : Table block tests scripts

- global.setup.js
Run nala tests on stage env in circle ci
> Run nala tests on stage env

- .github/workflows/daily.yml
- .github/workflows/debug.yml
- .github/workflows/manual.yml
- .github/workflows/self.yml
- features/milo/actionitem.block.spec.js
- global.setup.js
- selectors/milo/actionitem.block.page.js
- tests/milo/actionitem.block.test.js
- utils/reporters/base-reporter.js
[MWPW-139314](https://jira.corp.adobe.com/browse/MWPW-139314 ): Action-item Block tests scripts
PR includes 
- Automation test scripts for the following features of the Action-item block
1.    Action-item (small)
2.    Action-item (medium)
3.    Action-item (large)
4.    Action-item (center)
5.    Action-item (rounded)
6.    Action-item (float button)
7.    Action-item (scroller)
8.    Action-item (scroller with navigation)
- Updates to slack test run summary message
- Update .yaml's for slack webhook
> [MWPW-139314] : Action-item Block tests scripts

- features/milo/breadcrumbs.block.spec.js
- features/milo/footer.block.spec.js
- features/milo/header.block.spec.js
- tests/milo/breadcrumbs.block.test.js
- tests/milo/footer.block.test.js
- tests/milo/header.block.test.js
PR relates to ticket: [[MWPW-139561]: Run FEDS tests for every Milo PR when label is added](https://jira.corp.adobe.com/browse/MWPW-139561).
We hope this will add our critical component checks inside the CircleCI job testing scope as well.
> [MWPW-139561] FEDS to Milo: Run FEDS tests for every Milo PR when label is added

- features/milo/personalization.spec.js
- libs/webutil.js
- selectors/milo/merchcard.block.page.js
- selectors/milo/text.block.page.js
- tests/milo/personalization.feature.test.js
- utils/reporters/base-reporter.js
[MWPW-140157](https://jira.corp.adobe.com/browse/MWPW-140157): Personalization features tests scripts
PR includes 
- Automation test scripts for the Personalization features actions
1.    insertContentBefore
2.    insertContentAfter
3.    replaceContent
> [MWPW-140157] Personalization Test Scripts

- .github/workflows/cc.daily.yml
- configs/cc.config.js
- utils/reporters/base-reporter.js
MWPW-140218 : Update CC Daily run workflow
> MWPW-140218 : Update CC Daily run workflow

- features/milo/header.block.spec.js
- tests/milo/marquee.block.test.js
- tests/milo/media.block.test.js
This PR includes
- Update to filtering PR branch console errors 
- and introducing `@nopr` annotation for skipping test cases
> MWPW-140266 : Update PR branch console errors 

- .github/workflows/blog.daily.yml
- .github/workflows/cc.daily.yml
- .github/workflows/feds.daily.yml
- .github/workflows/milo.daily.yml
- configs/feds.config.js
- run.sh
- utils/reporters/base-reporter.js
[MWPW-140301](https://jira.corp.adobe.com/browse/MWPW-140301 ):  Create automated daily test run workflows for 'Feds' and 'Blog' in NALA
PR includes 
-  Daily test runs workflow for Feds
- Adjusted the workflow schedule for other projects 
- updated the` basereporter.js` for workflow name
> [MWPW-140301] Create automated daily test run workflows for 'Feds' and 'Blog' in NALA

- .github/workflows/uar.daily.yml
- configs/uar.config.js
- playwright.config.js
- utils/reporters/base-reporter.js
[MWPW-140301](https://jira.corp.adobe.com/browse/MWPW-140301 ):  Create automated daily test run workflows for 'Feds' 'UAR,' and 'Blog' in NALA
PR includes 
-  Daily test runs workflow for UAR
- Adjusted the workflow schedule for other projects 
- updated the` basereporter.js` for workflow name and minor defect fix
> [MWPW-140301] Create automated daily test run workflows for 'Feds', 'UAR', and 'Blog' in NALA

- features/cc/merchtable.spec.js
- selectors/cc/merchtable.page.js
- tests/cc/merchtable.test.js
CC Merch table block automation cases
JIRA : https://jira.corp.adobe.com/browse/MWPW-140978
Test run screen shot:
> CC Merchtable block automation

- features/helpx/beforeAfter.spec.js
- selectors/helpx/beforeafter.page.js
- tests/helpx/beforeafter.test.js
> Helpx_Before After Component Additional Test cases

- selectors/milo/icon.block.page.js
[MWPW-140826](https://jira.corp.adobe.com/browse/MWPW-140826): Update Icon Block tests scripts
PR includes 
- Update to icon block scripts as per the Jira: MWPW-140826
> [MWPW-140826] Update icon block scripts

- tests/milo/merchcard.block.test.js
PR Includes
[Merchcard] Update sepcial Offers Description locator
> [Merchcard] Update sepcial Offers Description locator

- tests/milo/video.block.test.js
PR Includes
[Video Block] Update video block test script to ignore console errors
> [Video Block] Update video block test script to ignore console errors

- libs/webutil.js
- tests/milo/commerce.feature.test.js
- tests/milo/video.block.test.js
PR includes
- Update to Nala Analytics test scripts / steps as per [PR MWPW-141781](https://github.com/adobecom/milo/pull/1785)
- Skipping Commerce  tests on PR branches
> [MWPW-141939][Analytics] Update to analytics test scripts as per Jira MWPW-141781

- tests/milo/merchcard.block.test.js
PR Includes
Fix to Merch Card Description - 3 Locator
> [Merch-card]: Fix Merch Card Description locator 

- selectors/milo/marquee.block.page.js
PR Includes:
- Update to Marquee block test scripts as per the [Milo PR MWPW-142630](https://github.com/adobecom/milo/pull/1867) changes media locator (` .media to .asset.`)
> [Marquee Block] Update to Marquee block test scripts as per the Milo changes media locator

- .github/workflows/run-lint.yml
Adding linter workflow to run on PRs.
> Adding linter workflow to run on PRs.

- selectors/acom/entitlement.commerce.page.js
- tests/acom/entitlement.commerce.test.js
Updated tests to use IMS paid user credentials
> refactoring for paid user entitlement

- utils/reporters/base-reporter.js
updated circleci link for nala test results report printout.
> Nala base reporter CircleCi url update

- package-lock.json
PR Includes
Fix to the Lockfile version.
> Fix Lockfile version

- configs/bacom.config.js
- Removed stage for bacom daily runs. 
- Temporarily commented out the bacom prod runs since some of the tests aren't using prod pages, which is causing failures in the daily run.
> Removed stage for bacom daily runs.

- .eslintrc.js
- tests/milo/table.block.test.js
PR includes
- Update table block flaky tests
- Removed the attribute validation line, as they are covered as part of other table validation steps.
> [Table Block] Update table block flaky tests

- configs/bacom.config.js
- selectors/bacom/stats.page.js
- tests/bacom/stats.test.js
- Updated stats selector 
- Increased timeout due to timeout failures when ran on browserstack
> Updating stats tests.

- tests/milo/accordion.block.test.js
- tests/milo/table.block.test.js
PR Includes: 
Fixes to Nala tests of the following blocks, which are failing as part of PR runs.
1. Accordion block tests:  Ignore the console error: `Attestation check for Topics on`
2. Table block tests: Update the attribute validation: `expect(await table.highlightRow).toHaveAttribute('class', 'row row-1 row-highlight');`
> MWPW-146230: Fix PR run failures

- features/milo/merchcard.block.spec.js
- selectors/milo/merchcard.block.page.js
- tests/milo/merchcard.block.test.js
PR Includes
- Update merch card nala tests as per the h3 and h4 changes 
- Ref PR : https://github.com/adobecom/milo/pull/2063
> [MWPW-146306] Update merch card h4 and h3 changes

- features/milo/merchcard.block.spec.js
- selectors/milo/merchcard.block.page.js
- tests/milo/merchcard.block.test.js
PR Includes
- Update merch card nala tests as per the h3 and h4 changes (A few more fixes )
- Ref PR: MWPW-144254 [merch-card] per type heading map milo#2063
> [MWPW-146306] Update merch card h4 and h3 changes (few more fixes)

- .github/workflows/bacom.daily.yml
Bacom daily run fixes after updating test dir path.
> Bacom daily fixes

- .github/workflows/bacom.daily.yml
Temporarily removing milo tests from bacom daily run.
> Removed milo tests from bacom daily run

- configs/bacom.config.js
Updated reporter to use base-reporter.js.
> Updated reporter

- configs/bacom.config.js
> Fixed base-reporter path.

- features/milo/georouting.spec.js
- run.sh
- tests/milo/marquee.block.test.js
PR includes:
- Enable the `@nopr` tag to skip running selected tests on the `PR branch`
Context:
- Nala UI tests related to console error validation, merchandise card price display, geo-routing modal display, and IMS Login do not work on PR branches.
- This PR introduces a feature to skip executing such tests on PR branches only.
-
How to Use:
- To skip tests, please add the annotation/tag `@nopr` to the corresponding test `.spec.js` file.
> MWPW-146763 : Enable @nopr tag to skip running selected tests on PR branch

- run.sh
PR includes, 
- Continuation of [PR : 326](https://github.com/adobecom/nala/pull/326) 
- Fixing the command as per GitHub shell
> [MWPW-146763][Continution] : Enable @nopr tag to skip running selected tests on PR branch

- features/milo/marketo.block.spec.js
- selectors/milo/marketo.block.page.js
- tests/milo/marketo.block.test.js
[MWPW-146473](https://jira.corp.adobe.com/browse/MWPW-146473)
Added tests for the new marketo form templates.
> Added tests for the new marketo forms templates

- features/milo/actionitem.block.spec.js
- selectors/milo/actionitem.block.page.js
- tests/milo/actionitem.block.test.js
[MWPW-146968](https://jira.corp.adobe.com/browse/MWPW-146968) 
- Added verification for the action item block's float button. 
- Updated test names in the test file.
- Removed unused floatIcon from page object.
> Added verification for the action item block's float button

- features/milo/marketo.block.spec.js
- selectors/milo/marketo.block.page.js
- tests/milo/marketo.block.test.js
Ticket: [MWPW-148005 ](https://jira.corp.adobe.com/browse/MWPW-148005)
Adding tests for the 'Company Type' field.
The field only displays when the hardcoded or selected Product of Interest is any of the following:
- Adobe Advertising Cloud
- Cross-channel Advertising
- Digital Commerce
> Adding tests for the company type field.

- selectors/milo/carousel.block.page.js
- tests/milo/carousel.block.test.js
- tests/milo/video.block.test.js
PR Includes:
- Update to Carousel block tests as per [Milo-PR](https://github.com/adobecom/milo/pull/2427) 
- Increased the carousel block `visibility wait time`
> [Carousel] Update the carousel block wait time for the visibility check

- selectors/milo/howto.block.page.js
- tests/milo/howto.block.test.js
Resolves: [MWPW-147299](https://jira.corp.adobe.com/browse/MWPW-147299)
`className` change in https://github.com/adobecom/milo/pull/2411 is breaking test.
This PR should fix.
> MWPW-147299

- libs/screenshot/compare.mjs
- libs/screenshot/merge.js
- libs/screenshot/uploads3.js
- libs/screenshot/utils.js
https://jira.corp.adobe.com/browse/MWPW-151940
> Fix security issue: Path traversal in JavaScript

- selectors/milo/howto.block.page.js
- tests/milo/howto.block.test.js
Reverts adobecom/nala#368. The corresponding milo PR isn't merged yet.
> Revert "MWPW-147299"

- selectors/milo/howto.block.page.js
- tests/milo/howto.block.test.js
Reverts adobecom/nala#374. Only merge when the corresponding Milo is merged.
> Revert "Revert "MWPW-147299""

- libs/screenshot/compare.mjs
- libs/screenshot/utils.js
> update screenshot diff failed

- configs/bacom.config.js
> Updated base reporter path.

- tests/milo/tab.block.test.js
The tab tests passes locally but there are failures in the github actions workflow.
> Fixing tab failures in github actions.

- .github/workflows/bacom.daily.yml
Updating tag to bacomSmoke due to other tests being picked up by the tag 'bacom'.
> Updating tag to bacomSmoke

- configs/bacom.config.js
- envs/envs.js
- selectors/bacom-blog/sharepoint.page.js
- tests/bacom/edit-sharepoint-doc.test.js
- Modifies scripts created for opening docx and modifying on bacom-blog for use on bacom
- Adds a step to utilize hlx sign in to ensure authentication 
Resolves: [MWPW-151549](https://jira.corp.adobe.com/browse/MWPW-151549)
> MWPW-151549: Modify blog playwright test for bacom

- features/milo/marketo.block.spec.js
- selectors/milo/marketo.block.page.js
- tests/milo/marketo.block.test.js
Ticket: [MWPW-153156](https://jira.corp.adobe.com/browse/MWPW-153156) 
The old form template tests are no longer needed so I'm removing the tests.
> Removed old form template test.

- tests/milo/tab.block.test.js
> Fixing failing tab tests.

- configs/dme.config.js
- envs/envs.js
- features/dme/announcements.spec.js
- selectors/dme/announcements.page.js
- tests/dme/announcements.test.js
PR includes
initial folder structure for DME-partners project: https://github.com/adobecom/dme-partners
> initial commit for dme-partners project

- features/bacom/marketo-stage.spec.js
- selectors/milo/marketo.block.page.js
- tests/bacom/marketo-stage.test.js
Adding tests for marketo stage form.
> Adding tests for marketo stage form.

- .eslintrc.js
- tests/milo/accordion.block.test.js
- tests/milo/personalization.feature.test.js
- tests/milo/video.block.test.js
PR includes
- skipping personalization test on chrome browser
- disabling console error validation for video block
> disable console log error validation for video block 

- tests/milo/promotions.feature.test.js
Skipping the one failing promo test on chromium browser until the cause of failure is found.
> Skip failing promo test

- tests/milo/media.block.test.js
PR Includes
-  Removed console error count check for media block on pr branches
>  Removed console error count check for media block on pr branches

- tests/milo/marketo.block.test.js
Updating the POI used in the test due to form changes.
> Updating POI due to form changes.

- data/dc/sot-basic.yml
- features/visual/dc/sot.spec.js
- tests/visual/dc/sot.test.js
> add dc screenshots

- features/milo/accordion.block.spec.js
- selectors/milo/accordion.block.page.js
- tests/milo/accordion.block.test.js
- tests/milo/table.block.test.js
[PR Includes](https://jira.corp.adobe.com/browse/MWPW-154485)
- [MWPW-154485] Add Accordion seo editorial test
- Fix to Table block test: Table (highlight, collapse, sticky)
> [MWPW-154485] Add Accordion seo editorial test

- features/bacom/e2e/marketo.spec.js
- runOnBrowserstack.sh
[MWPW-155726
](https://jira.corp.adobe.com/browse/MWPW-155726) 
Adding sh script to run tests on browserstack.
> Adding sh script to run tests on browserstack.

- run.js
Adding debug option to run.js.
> Adding debug option

- features/milo/marketo.block.spec.js
- selectors/milo/marketo.block.page.js
- tests/bacom/e2e/marketo.e2e.test.js
- tests/milo/marketo.block.test.js
[MWPW-155727](https://jira.corp.adobe.com/browse/MWPW-155727)
Adding tests for Marketo forms thank you message.
-  The form shouldn't redirect after a successful submission.
- The thank you message should display after form submission.
> Adding marketo messages tests

- run.js
Adding the option to run tests in browserstack using run.js.
> Adding bstack option to run.js

- tests/milo/marketo.block.test.js
Fixes failures in [this](https://github.com/adobecom/milo/actions/runs/10467634836/job/28986809754?pr=2761 ) test run due to cases.
> Fixing failures due to cases.

- features/milo/commerce.spec.js
- tests/milo/commerce.feature.test.js
Adding test case for commerce in UK locale due to its commerce logic difference in comparison to all other locales
> warriors: add commerce test for UK locale

- tests/milo/video.block.test.js
[PR Includes](https://jira.corp.adobe.com/browse/MWPW-157786)
- Fixes to Video Block
- Add console error ignore for Marquee block
> [MWPW-157786]Fix video block failures

- features/milo/video.block.spec.js
- selectors/milo/video.block.page.js
- tests/milo/video.block.test.js
[PR Includes](https://jira.corp.adobe.com/browse/MWPW-157786)
- Fixes to Video Block failures
- YouTube and MPC Video variants
> [MWPW-157786]Fix video block youtube and mpc variants

- features/milo/commerce.spec.js
- tests/milo/commerce.feature.test.js
https://jira.corp.adobe.com/browse/MWPW-157754
adding test case that can be run on ALL locales on Jenkins that is checking placeholders are resolved. The environment variable `loc` will be added through the jenkins job.
> commerce: add test for loc Jenkins job

- features/bacom/features/dynamic-nav.spec.js
- tests/bacom/edit-sharepoint-doc.test.js
- Updating tags to include dynamic nav in the daily run.
> Updating tags

- tests/bacom/headers.test.js
- tests/bacom/redirects.test.js
These tests are currently failing when ran on Github actions. Skipping for now.
> Skipping tests on github actions for now.

- features/bacom/e2e/marketo.e2e.spec.js
Updating marketo essentials form test path.
> Updating marketo essentials form test path.

- selectors/feds/feds.header.page.js
- tests/bacom/e2e/marketo.e2e.test.js
- tests/bacom/features/dynamic-nav.test.js
[MWPW-163896](https://jira.corp.adobe.com/browse/MWPW-163896
) 
- Updating dynamic nav tests to exclude the status 
- Removed an extra "?" in marketo tests
> Updating dynamic nav tests to exclude status

- features/milo/video.block.spec.js
- selectors/milo/marquee.block.page.js
- tests/milo/marquee.block.test.js
[MWPW-164409
](https://jira.corp.adobe.com/browse/MWPW-164409)
Fixes tests with the new video pause button.
> Fixes tests with the new video pause button.

- features/milo/commerce.spec.js
- features/milo/htmlextn.spec.js
- features/milo/ost.tools.spec.js
- package-lock.json
- package.json
- selectors/milo/merchcard.block.page.js
- tests/milo/merchcard.block.test.js
PR fixes 
- [Kodiak][R4]: CVE-2024-39338 in [github.com/adobecom/nala]
- And commerce test
- Playwright install issues on GitHub runs and daily runs 
- Upgraded the playwright version    
Context: 
High severity - Server-side Request Forgery (SSRF) vulnerability in axios
Introduced through: nala@1.0.0 › axios@1.6.7
Remediation: upgrade `axios` to version 1.7.4 or higher.
> [MWPW-156780] Fix axios version upgrade

- .github/workflows/bacom.daily.yml
- .github/workflows/bacom.milolibs.run.yml
- .github/workflows/blog.daily.yml
- .github/workflows/caas.daily.yml
- .github/workflows/cc.daily.yml
- .github/workflows/debug.yml
- .github/workflows/express.daily.yml
- .github/workflows/feds.daily.yml
- .github/workflows/helpx.daily.yml
- .github/workflows/manual.yml
- .github/workflows/milo.daily.yml
- .github/workflows/milolib.yml
- .github/workflows/saucelabs.yml
- .github/workflows/self.yml
- .github/workflows/uar.daily.yml
[MWPW-165833](https://jira.corp.adobe.com/browse/MWPW-165833) 
Updating upload-artifact from v3 to v4 since v3 is being deprecated.
> Updating  upload-artifact to v4.

- selectors/milo/tabs.block.page.js
[MWPW-166699](https://jira.corp.adobe.com/browse/MWPW-166699)
Fixing failing tabs tests.
> Fixing tabs tests.

- tests/milo/breadcrumbs.block.test.js
[MWPW-166969](https://jira.corp.adobe.com/browse/MWPW-166969)
The breadcrumb tests are failing on the daily runs. Updating breadcrumb regex.
> Updating breadcrumbs regex

- .github/workflows/run-lint.yml
PR Includes
- Update the ESLint GitHub Action to address the vulnerability.
> Update the ESLint GitHub Action to address the vulnerability.

- .github/workflows/run-lint.yml
- selectors/milo/marketo.block.page.js
- tests/milo/marketo.block.test.js
[MWPW-142682 ](https://jira.corp.adobe.com/browse/MWPW-142682)
Adding Marketo error messages check.
> Adding Marketo error messages check

- configs/express.config.js
- selectors/express/image-list.page.js
- tests/express/image-list.test.js
Update destination URL for image click for image-list block (Adobe Express block).
> image-list tests: update destination url

- features/milo/promotions.spec.js
- features/milo/video.block.spec.js
- selectors/milo/aside.block.page.js
- selectors/milo/merchcard.block.page.js
- selectors/milo/promotions.feature.page.js
- selectors/milo/video.block.page.js
- tests/milo/aside.block.test.js
- tests/milo/promotions.feature.test.js
- tests/milo/quote.block.test.js
- tests/milo/text.block.test.js
- tests/milo/video.block.test.js
PR includes
- Fixes for Milo Video tests for BACOM daily run
- Fixed some line spacing issues in text and quote block tests
> [Milo][Video] Fix Milo Video tests for BACOM daily run

- features/express/gen-ai-cards.spec.js
- selectors/express/gen-ai-cards.page.js
- tests/express/gen-ai-cards.test.js
http://jira.corp.adobe.com/browse/MWPW-171728
> Adobe Express - gen-ai-cards block

- features/express/simplified-pricing-cards.spec.js
- selectors/express/simplified-pricing-cards.page.js
- tests/express/simplified-pricing-cards.test.js
https://jira.corp.adobe.com/browse/MWPW-172571
> simplified pricing cards

- features/cc/photoshop-unity.spec.js
- selectors/cc/photoshop-unity.page.js
- tests/cc/photoshop-unity.test.js
Added a dedicated test case for the remove background feature & product page in CCPhotoshopUnity.
> CCPhotoshopUnity Test: Remove Background Page

- features/caas/caas.spec.js
- selectors/caas/caas.feature.page.js
Fix failing CaaS test case in NALA.
Resolves: [MWPW-175082](https://jira.corp.adobe.com/browse/MWPW-175082)
> MWPW-175082: Automation test in NALA is failing
