adobecom/nala

package-lock.json
package.json

Added support for following npm run commands for tests
- `npm run test:chrome` : Runs all tests on chrome browser in gui mode
- `npm run test:firefox`  : Runs all tests on firefox browser in gui mode
- `npm run test:safari` : Runs all tests on safari browser in gui mode
- `npm run test:chrome-headless` : Runs all tests on chrome browser in headless mode 
- `npm run test:firefox-headless`  :  Runs all tests on firefox browser in headless mode
- `npm run test:safari-headless` : Runs all tests on safari browser in headless mode
- `npm run test:gui` : Runs all tests on all browsers in gui mode
Note : User can add additional tags to above command to choose specific tests.

Configure browser specific npm run commands

---

.github/workflows/debug.yml

added debugging GitHub actions workflow
- Workflow that can be executed on demand and not on schedules or pull requests
- the ability to send in test tags as inputs
- uploading execution report for playwright trace viewer

added debugging github actions

---

envs/envs.js
features/faas.spec.js
tests/faas.test.js

removed test to remove long timeouts by changing milo environment testing to milo prod.  Removed webkit conditional as well now that it is on prod.

FaaS Test Timeout Fix

---

envs/envs.js
runLocalRegression.sh

Adding options to run Nala tests against localhost 3000 and 6456. 
Ticket: https://jira.corp.adobe.com/browse/MWPW-119683  
In order to test against localhost, the user would have to run the runLocalRegression.sh script. If they don't specify a tag with the -t flag, it'll run all tests. If the 6456 port isn't specified with the -p flag, it'll default to port 3000. 
What the script does: 
1. Updates the envs line in ".feature" files to add either "@localhost:3000" or "@localhost:6456" and comments the existing value out. 
2. It then runs the tests against localhost.
3. It then reverts the envs back to their previous value.

Added options to run tests against localhost.

---

tests/failedblock.test.js

- Removed hover method and instead created scroll method.  The scroll method provides time for all elements to load that lazy load to ensure failedblock.js gets to run for the full page.
- Changed expect() method to expect.soft() so the rest of the test will run if a failed block is found.  This allows the test to still fail if a failed block is found and prints out the browser type, the content of the failed block.

Failed block fix for webkit executions

---

features/parse.js
tests/dc_converter.test.js

Removed workaround for CSP issue with DC hlx.* urls when testing for Milo or any other consuming site but DC's repository.

Removed workaround for CSP issue

---

selectors/marquee.selectors.js

* NOTE: This PR relates directly to [#503 in the milo repo](https://github.com/adobecom/milo/pull/503) and SHOULD NOT be merged until the PR in milo is merged and then consumed here.
* Updates all JS files that set classnames to use lowercase t-shirt sizes
* Should allow us to get a clearer picture of style-linting errors moving forward
Resolves: [MWPW-126441](https://jira.corp.adobe.com/browse/MWPW-126441)
**Test URLs:**
(Note that these should both look the same, but the After view uses lowercase t-shirt size classnames)
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/media?martech=off
- After: https://ebartholomew-kebab-case-tshirts--milo--adobecom.hlx.page/docs/library/blocks/media?martech=off

[MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames

---

features/html_ext.spec.js
tests/html_ext.test.js

This PR addresses the found issue in this ticket: [MWPW-127111](https://jira.corp.adobe.com/browse/MWPW-127111)
* Added regex checking for HTML extensions when using locales in /blog/ URLs
* Added JP URL to test HTML extension in a different locale.

HTML extension test uses locale urls

---

tests/milo/faas.test.js
tests/milo/modal.test.js

fixed failing tests in daily runs:
- FaaS test holiday shopping report conditional name was changed from @html to @html-ext
- Modal test cases were split into two tests so that a test.skip() could be added for one of the tests that fail for webkit due to the current playwright trunk build for v16.4 1792.  The modal doesn't close using the Esc key.

Daily Run test fixes

---

.github/workflows/self.yml

Currently, Nala tests are run if PR has the label: `run-nala`, this is now enhanced to below
Jira : [MWPW-128629](https://jira.corp.adobe.com/browse/MWPW-128629)
User will able to run Nala tests if PR has the any label(s) in below format
- No need to have a separate label: `nala-run` to trigger the test run job
-  PR labels 
- labels = `run-dc` or` run-nala` or `run-milo` etc  will trigger the test run job and executes tests corresponding all projects specified in config.js
- labels = `run-milo-live` or `run-nala-milo-live` or `run-dc-stage` or `run-dc-live` etc  will trigger the test run job and executes tests corresponding to projects [ like live, stage etc] of specified in config.js
- labels = `run-milo-live`, `@carousel-container`, `@smoke`  will trigger the test run job and executes …

MWPW-128629 : Update github self.yml job run check condition

---

selectors/milo/media.block.page.js

PR fixes the below issue:
**Issue:** Media block  test script: media (Small), was failing due to an update in CSS font for `body-s` and outline button `color` to `rgb(44, 44, 44)`

Fix media (small) block CSS font and color step failing

---

tests/milo/aside.block.test.js

- PR raised in order to fix failing Aside check (`aside-split-large`) & enable another check which was skipped because of technical reasons (`aside-split-large-half-dark`)
- PR raised in scope of ticket [[MWPW-133606](https://jira.corp.adobe.com/browse/MWPW-133606)]: Aside Block: Create Nala Automation Test script.

[MWPW-133606] Updated Aside checks (fix failing checks)

---

tests/milo/marketo.block.test.js

Removing the skip for Firefox because the tests no longer fail.

Removing skip for the Marketo form Firefox tests

---

package-lock.json
package.json

This PR includes
Upgrade the playwright version to 1.42 
Note:
- Browserstack SDK is supported in latest version of playwright i.e. 1.42
- https://playwright.dev/docs/release-notes#version-142

[MWPW-144049] : Upgrade playwright version to 1.42

---

configs/bacom.config.js

[MWPW-145790](https://jira.corp.adobe.com/browse/MWPW-145790)
Enabing milo tests on bacom.

Enabing milo tests on bacom

---

selectors/milo/marketo.block.page.js
tests/milo/marketo.block.test.js
tests/milo/tab.block.test.js

[MWPW-146325 ](https://jira.corp.adobe.com/browse/MWPW-146325)
Fixes tab scrolling and Marketo form failures on daily runs.
- The tab scrolling passes locally. Adding longer interval times to see if that helps the github run.
- Marketo forms has a rate limit which is why it was failing with so many parallel runs. Added wait time and updated to the recommended email format.

Marketo and Tabs daily run fixes.

---

configs/bacom-blog.config.js
features/bacom-blog/language-menu.spec.js
selectors/bacom-blog/language-menu.page.js
tests/bacom-blog/language-menu.test.js

[MWPW-146487
](https://jira.corp.adobe.com/browse/MWPW-146487)
Adding region selector tests for bacom blog.
- Selecting the menu button should open the menu
- The language menu should be able to close by selecting the menu button
- Selecting a language option should redirect the user to the respective locale.

Adding region selector tests for bacom blog.

---

selectors/bacom-blog/sharepoint.page.js
tests/bacom-blog/edit-sharepoint-doc.test.js

Adding sharepoint editing script for bacom-blog. 
Ticket: [MWPW-147160](https://jira.corp.adobe.com/browse/MWPW-147160)
This script will:
1. Read the urls from a json file. 
2. Loop through each url. 
3. Go to the admin page to get the sharepoint url. 
4. Go to the sharepoint url.
5. Add a page break and save the file.
6. Undo the change and save the file.

Adding sharepoint editing script

---

tests/bacom/event-speakers.test.js
tests/bacom/stats.test.js
tests/bacom/tree-view.test.js
tests/milo/marketo.block.test.js

I went through the milo and bacom tests and these were the ones that were still missing the milolibs param.

Enable tests to run with the milolibs param

---

selectors/milo/marketo.block.page.js
tests/milo/marketo.block.test.js

[MWPW-151436](https://jira.corp.adobe.com/browse/MWPW-151436)
Adding checks for the Marketo forms input field's placeholders.

Adding Marketo placeholder tests

---

.eslintrc.js
.github/workflows/saucelabs.yml
features/milo/htmlextn.spec.js
playwright.config.js
selectors/milo/merchcard.block.page.js
tests/milo/htmlextn.feature.test.js
tests/milo/merchcard.block.test.js
tests/milo/video.block.test.js

PR Includes
- Update and Fix for .eslintrc.js rules
- Updated/Removed the triggering of ` sauceclt job ` from GitHub action jobs upon PR
- Fix of eslint errors for `marchcard.block.test.js`, `htmlextn.feature.test.js`, `playwright.config.js`
- Update to the `number of retries` for failures in playwright.config.js 
- Skip of merch-cards and htmlextn feature tests on Chrome browser headless mode only due to` [http](net::ERR_HTTP2_PROTOCOL_ERROR)` [ This is a workaround till we find a solution]
- Updated the `video.block.test.js` , updated the timeout for the mpc-mute button

Update the config for timeout errors

---

features/bacom/event-speakers.spec.js
features/bacom/stats.spec.js
features/bacom/tree-view.spec.js

Adding a 'bacomSmoke' tag to differentiate the tests from bacom-blog since the tag 'bacom' will pick up the bacom-blog tests as well.

Adding bacomSmoke tag

---

configs/bacom-blog.config.js
configs/bacom.config.js
features/bacom/stats.spec.js

Updating base reporter.

---

run.js

Adding list option to run.js. List will list out all tests found, but doesn't run them.

Adding list option to run.js

---

tests/milo/commerce.feature.test.js
tests/milo/merchcard.block.test.js

Resolving net::ERR_HTTP2_PROTOCOL_ERROR that caused us to skip merch block and commerce tests in chromium.
The request for https://www.adobe.com/federal/commerce/price-literals.json was failing due to the headless mode. Removing HeadlessChrome version from the user agent branding with the header override.
The original header in github actions run:
```
{
"name": "sec-ch-ua",
"value": "\"HeadlessChrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""
},
```

resolve ERR_HTTP2_PROTOCOL_ERROR

---

configs/bacom.config.js
features/milo/marketo.block.spec.js
selectors/milo/marketo.block.page.js
tests/milo/marketo.block.test.js

[MWPW-158226](https://jira.corp.adobe.com/browse/MWPW-158226)
Updating Marketo message tests to reflect the updates to the block. 
-  The title, description, and fields should now be hidden after a successful form submission.
- Added testMatch to locate tests under the milo and bacom directories.

Updating Marketo message tests

---

features/bacom/features/dynamic-nav.spec.js
tests/bacom/features/dynamic-nav.test.js

[MWPW-158414](https://jira.corp.adobe.com/browse/MWPW-158414)
Adding tests for dynamic navigation.
- Navigating from an entry page to an "on" page should retain the entry page's nav and have breadcrumbs disabled.
- Navigating from an entry page to an "on" page with dynamic nav disabled shouldn't retain the entry page's nav.

Adding tests for dynamic nav

---

.github/workflows/bacom.daily.yml

The bacom's daily windows run is picking up more than the specified tags in the daily run, causing it to run for an hour.

Removing windows from bacom's daily platform matrix.

---

selectors/milo/accordion.block.page.js

[MWPW-168575](https://jira.corp.adobe.com/browse/MWPW-168575) 
The accordion tests are failing due to a change in the tags used. We're no longer using the dt tag, see [PR 3613](https://github.com/adobecom/milo/pull/3613) .

Accordion fixes

---

.github/workflows/bacom.daily.yml
.github/workflows/bacom.milolibs.run.yml
.github/workflows/blog.daily.yml
.github/workflows/caas.daily.yml
.github/workflows/cc.daily.yml
.github/workflows/debug.yml
.github/workflows/express.daily.yml
.github/workflows/feds.daily.yml
.github/workflows/helpx.daily.yml
.github/workflows/manual.yml
.github/workflows/milo.daily.yml
.github/workflows/milolib.yml
.github/workflows/run-lint.yml
.github/workflows/run-screendiff.yml
.github/workflows/saucelabs.yml
.github/workflows/self.yml
.github/workflows/uar.daily.yml

PR Includes
Following this [incident](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066), we want to harden the security for our Github actions by [pinning actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) to full length commit SHAs. It's the recommended approach in terms of security from Github, and while we won't get any minor versions of OOTB, security and stability are more important than the latest and greatest features in this case.

[MWPW-170017][ActionRuns] Update the GitHub Actions to address the vulnerability

---

features/milo/marketo.block.spec.js
selectors/milo/marketo.block.page.js
tests/milo/marketo.block.test.js

[MWPW-173108 
](https://jira.corp.adobe.com/browse/MWPW-173108) 
Adding marketo show hide test. The specified content should be shown and hidden after a successful form submission.

Adding marketo show hide test

---

features/bacom/e2e/marketo.e2e.spec.js

The uk homepage is now using an essentials form. Updating to match the content update.

Updating uk form to match content change.

---

features/bacom/e2e/marketo.e2e.spec.js
features/bacom/headers.spec.js

- Updating header test origin for event pages. 
- Updating test pages for Marketo tests on bacom.

Updating header test origin and marketo test pages
